// FTP VIDEO WON — Playlist Data
// Auto-updated by PLister v2
// 2026-03-23 15:32:21
const TRACKS = [
  {"id": "ClngWDLgls4", "title": "Come on sl#ts", "artist": "Come on sl#ts", "song": "Come on sl#ts", "genre": "ALT", "start": 0, "end": 204},
  {"id": "ClngWDLgls4", "title": "Chicks want to hit the beach", "artist": "Chicks want to hit the beach", "song": "Chicks want to hit the beach", "genre": "ALT", "start": 204, "end": 424},
  {"id": "ClngWDLgls4", "title": "Why I'm dressed up", "artist": "Why I'm dressed up", "song": "Why I'm dressed up", "genre": "ALT", "start": 424, "end": 581},
  {"id": "ClngWDLgls4", "title": "Big Decks", "artist": "Big Decks", "song": "Big Decks", "genre": "ALT", "start": 581, "end": 800},
  {"id": "ClngWDLgls4", "title": "Pussy in the Club", "artist": "Pussy in the Club", "song": "Pussy in the Club", "genre": "ALT", "start": 800, "end": 1010},
  {"id": "ClngWDLgls4", "title": "Evo", "artist": "Evo", "song": "Evo", "genre": "ALT", "start": 1010, "end": 1169},
  {"id": "ClngWDLgls4", "title": "Deep in the Club", "artist": "Deep in the Club", "song": "Deep in the Club", "genre": "ALT", "start": 1169, "end": 1342},
  {"id": "ClngWDLgls4", "title": "Richard's Intro", "artist": "Richard's Intro", "song": "Richard's Intro", "genre": "ALT", "start": 1342, "end": 1542},
  {"id": "ClngWDLgls4", "title": "Like a Man (Remix)", "artist": "Like a Man (Remix)", "song": "Like a Man (Remix)", "genre": "ALT", "start": 1542, "end": 1807},
  {"id": "ClngWDLgls4", "title": "Tech Scratch (outro)", "artist": "Tech Scratch (outro)", "song": "Tech Scratch (outro)", "genre": "ALT", "start": 1807, "end": 1897},
  {"id": "M_agcU3jLH8", "title": "Intro", "artist": "Intro", "song": "Intro", "genre": "ALT", "start": 0, "end": 66},
  {"id": "M_agcU3jLH8", "title": "Rays", "artist": "Rays", "song": "Rays", "genre": "ALT", "start": 66, "end": 270},
  {"id": "M_agcU3jLH8", "title": "Let Go", "artist": "Let Go", "song": "Let Go", "genre": "ALT", "start": 270, "end": 542},
  {"id": "M_agcU3jLH8", "title": "City", "artist": "City", "song": "City", "genre": "ALT", "start": 542, "end": 849},
  {"id": "M_agcU3jLH8", "title": "Good Luck", "artist": "Good Luck", "song": "Good Luck", "genre": "ALT", "start": 849, "end": 1152},
  {"id": "M_agcU3jLH8", "title": "So Easy", "artist": "So Easy", "song": "So Easy", "genre": "ALT", "start": 1152, "end": 1423},
  {"id": "M_agcU3jLH8", "title": "Podium", "artist": "Podium", "song": "Podium", "genre": "ALT", "start": 1423, "end": 1679},
  {"id": "mJzvcnwU1nU", "title": "KĀHU — ᴅᴜɴᴇᴅɪɴ ᴊᴀᴢᴢ ʟᴏꜰᴛ: ɪɴᴅɪᴇ ᴠᴏɪᴄᴇꜱ ɪɪ", "artist": "KĀHU", "song": "KĀHU — ᴅᴜɴᴇᴅɪɴ ᴊᴀᴢᴢ ʟᴏꜰᴛ: ɪɴᴅɪᴇ ᴠᴏɪᴄᴇꜱ ɪɪ", "genre": "ALT", "start": 0, "end": 1655},
  {"id": "SLsg2lt_wC8", "title": ":01", "artist": ":01", "song": ":01", "genre": "ALT", "start": 0, "end": 3},
  {"id": "SLsg2lt_wC8", "title": ":20", "artist": ":20", "song": ":20", "genre": "ALT", "start": 3, "end": 9},
  {"id": "SLsg2lt_wC8", "title": ":27", "artist": ":27", "song": ":27", "genre": "ALT", "start": 9, "end": 1553},
  {"id": "Ptyeyq1d33s", "title": "E-kare (Live From The Crown)", "artist": "E-kare (Live From The Crown)", "song": "E-kare (Live From The Crown)", "genre": "ALT", "start": 0, "end": 1172},
  {"id": "4wKDSf3GKIM", "title": "Robots in Love (Live From The Crown)", "artist": "Robots in Love (Live From The Crown)", "song": "Robots in Love (Live From The Crown)", "genre": "ALT", "start": 0, "end": 1690},
  {"id": "1uKp4Tems4M", "title": "So Easy", "artist": "So Easy", "song": "So Easy", "genre": "ALT", "start": 0, "end": 221},
  {"id": "1uKp4Tems4M", "title": "Good Luck", "artist": "Good Luck", "song": "Good Luck", "genre": "ALT", "start": 221, "end": 514},
  {"id": "1uKp4Tems4M", "title": "The City", "artist": "The City", "song": "The City", "genre": "ALT", "start": 514, "end": 814},
  {"id": "1uKp4Tems4M", "title": "Rays", "artist": "Rays", "song": "Rays", "genre": "ALT", "start": 814, "end": 1008},
  {"id": "1uKp4Tems4M", "title": "Burn", "artist": "Burn", "song": "Burn", "genre": "ALT", "start": 1008, "end": 1302},
  {"id": "1uKp4Tems4M", "title": "Podium", "artist": "Podium", "song": "Podium", "genre": "ALT", "start": 1302, "end": 1587},
  {"id": "3OS_XOca06o", "title": "DENNIS DENUTO - WMFLive #bassmusic", "artist": "DENNIS DENUTO", "song": "WMFLive #bassmusic", "genre": "DJ", "start": 0, "end": 2062},
  {"id": "5TtnJgGc_yE", "title": "Ridge Jaggers - Froth Mouth Weekend #Ghetto #bass", "artist": "Ridge Jaggers", "song": "Froth Mouth Weekend #Ghetto #bass", "genre": "DJ", "start": 0, "end": 2628},
  {"id": "alOiYGYrCes", "title": "Jay Knight (DJ set) — ŌHHH24 #hiphop", "artist": "Jay Knight (DJ set)", "song": "Jay Knight (DJ set) — ŌHHH24 #hiphop", "genre": "DJ", "start": 0, "end": 2953},
  {"id": "9pcypLIayUU", "title": "Ridge Jaggers (DJ set) - ŌHHH24 #hiphop", "artist": "Ridge Jaggers (DJ set)", "song": "ŌHHH24 #hiphop", "genre": "DJ", "start": 0, "end": 1111},
  {"id": "rbDQt34jI7c", "title": "Levine Lale (DJ set) - ŌHHH24 #hiphop", "artist": "Levine Lale (DJ set)", "song": "ŌHHH24 #hiphop", "genre": "DJ", "start": 0, "end": 3156},
  {"id": "f8fhAe6YrTw", "title": "Ferdishenko —  WMFLive #bassmusic", "artist": "Ferdishenko", "song": "Ferdishenko —  WMFLive #bassmusic", "genre": "DJ", "start": 0, "end": 1666},
  {"id": "AFYyCTUdDuQ", "title": "DJ Shan — ŌHHH22", "artist": "DJ Shan", "song": "DJ Shan — ŌHHH22", "genre": "DJ", "start": 0, "end": 1017},
  {"id": "dx1OdF7DkyM", "title": "The Horse — ŌHHH22", "artist": "The Horse", "song": "The Horse — ŌHHH22", "genre": "DJ", "start": 0, "end": 1261},
  {"id": "7yn0uq2h3_0", "title": "Ridge Jaggers - BootyBass GhettoTech (live)", "artist": "Ridge Jaggers", "song": "BootyBass GhettoTech (live)", "genre": "DJ", "start": 0, "end": 1811},
  {"id": "8e-Q_dpbr9o", "title": "Nick Knox   Shine On   C39", "artist": "Nick Knox   Shine On   C39", "song": "Nick Knox   Shine On   C39", "genre": "EVENT", "start": 0, "end": 5400},
  {"id": "4BhRPFwLHHE", "title": "Sleeping Dogs", "artist": "Sleeping Dogs", "song": "Sleeping Dogs", "genre": "FOLK", "start": 335, "end": 706},
  {"id": "4BhRPFwLHHE", "title": "Athena", "artist": "Athena", "song": "Athena", "genre": "FOLK", "start": 706, "end": 1073},
  {"id": "4BhRPFwLHHE", "title": "Oisín (Tír na nÓg)", "artist": "Oisín (Tír na nÓg)", "song": "Oisín (Tír na nÓg)", "genre": "FOLK", "start": 1073, "end": 1474},
  {"id": "4BhRPFwLHHE", "title": "Black Mountain", "artist": "Black Mountain", "song": "Black Mountain", "genre": "FOLK", "start": 1474, "end": 1810},
  {"id": "4BhRPFwLHHE", "title": "Lands", "artist": "Lands", "song": "Lands", "genre": "FOLK", "start": 1810, "end": 2115},
  {"id": "9ZCRRkrIM2k", "title": "CATHERINE KS — ᴅᴜɴᴇᴅɪɴ ᴊᴀᴢᴢ ʟᴏꜰᴛ: ɪɴᴅɪᴇ ᴠᴏɪᴄᴇꜱ ɪɪ", "artist": "CATHERINE KS", "song": "CATHERINE KS — ᴅᴜɴᴇᴅɪɴ ᴊᴀᴢᴢ ʟᴏꜰᴛ: ɪɴᴅɪᴇ ᴠᴏɪᴄᴇꜱ ɪɪ", "genre": "FOLK", "start": 0, "end": 2241},
  {"id": "IQGXKkpUz4A", "title": "SWINGBRIDGE — ᴅᴜɴᴇᴅɪɴ ᴊᴀᴢᴢ ʟᴏꜰᴛ: ɪɴᴅɪᴇ ᴠᴏɪᴄᴇꜱ ɪɪ", "artist": "SWINGBRIDGE", "song": "SWINGBRIDGE — ᴅᴜɴᴇᴅɪɴ ᴊᴀᴢᴢ ʟᴏꜰᴛ: ɪɴᴅɪᴇ ᴠᴏɪᴄᴇꜱ ɪɪ", "genre": "FOLK", "start": 0, "end": 1645},
  {"id": "ZIsbq6WGWPQ", "title": "Catgut and Steel (Live From The Crown)", "artist": "Catgut and Steel (Live From The Crown)", "song": "Catgut and Steel (Live From The Crown)", "genre": "FOLK", "start": 0, "end": 1631},
  {"id": "y3-LF-9y1Vw", "title": "Not Lost", "artist": "Not Lost", "song": "Not Lost", "genre": "FOLK", "start": 1, "end": 238},
  {"id": "y3-LF-9y1Vw", "title": "Dead of Night", "artist": "Dead of Night", "song": "Dead of Night", "genre": "FOLK", "start": 238, "end": 530},
  {"id": "y3-LF-9y1Vw", "title": "Get Older", "artist": "Get Older", "song": "Get Older", "genre": "FOLK", "start": 530, "end": 805},
  {"id": "y3-LF-9y1Vw", "title": "Searching for a Saint", "artist": "Searching for a Saint", "song": "Searching for a Saint", "genre": "FOLK", "start": 805, "end": 1055},
  {"id": "y3-LF-9y1Vw", "title": "Keep On", "artist": "Keep On", "song": "Keep On", "genre": "FOLK", "start": 1055, "end": 1299},
  {"id": "DfMNRhoVt7k", "title": "The Little Smith Band - Lobofest 21", "artist": "The Little Smith Band", "song": "Lobofest 21", "genre": "FOLK", "start": 0, "end": 1933},
  {"id": "PhiX-sWXDyM", "title": "EXPJ - (Expensive Jazz Ft JAH SUN )  'Keep Breathing' (LYRIC VID)", "artist": "EXPJ", "song": "(Expensive Jazz Ft JAH SUN )  'Keep Breathing' (LYRIC VID)", "genre": "JAZZ", "start": 0, "end": 522},
  {"id": "2pRETqjNATo", "title": "EXPJ - Expensive Jazz 5 [放鬆 BGM 作業用 ]", "artist": "EXPJ", "song": "Expensive Jazz 5 [放鬆 BGM 作業用 ]", "genre": "JAZZ", "start": 0, "end": 1261},
  {"id": "6znXM0PiPrg", "title": "intro", "artist": "intro", "song": "intro", "genre": "JAZZ", "start": 0, "end": 1020},
  {"id": "6znXM0PiPrg", "title": "Small Town Street Light", "artist": "Small Town Street Light", "song": "Small Town Street Light", "genre": "JAZZ", "start": 1020, "end": 2672},
  {"id": "6znXM0PiPrg", "title": "Reprisal", "artist": "Reprisal", "song": "Reprisal", "genre": "JAZZ", "start": 2672, "end": 3244},
  {"id": "Y1HIFa3CNNI", "title": "Expensive Jazz - Can't Wait (23 01 17)", "artist": "Expensive Jazz", "song": "Can't Wait (23 01 17)", "genre": "JAZZ", "start": 0, "end": 888},
  {"id": "uhFob1qiNio", "title": "Begins", "artist": "Begins", "song": "Begins", "genre": "JAZZ", "start": 0, "end": 1305},
  {"id": "uhFob1qiNio", "title": "Expansive", "artist": "Expansive", "song": "Expansive", "genre": "JAZZ", "start": 1305, "end": 1595},
  {"id": "uhFob1qiNio", "title": "Introductions", "artist": "Introductions", "song": "Introductions", "genre": "JAZZ", "start": 1595, "end": 1993},
  {"id": "uhFob1qiNio", "title": "Step", "artist": "Step", "song": "Step", "genre": "JAZZ", "start": 1993, "end": 2220},
  {"id": "uhFob1qiNio", "title": "Meander", "artist": "Meander", "song": "Meander", "genre": "JAZZ", "start": 2220, "end": 2551},
  {"id": "uhFob1qiNio", "title": "Roll", "artist": "Roll", "song": "Roll", "genre": "JAZZ", "start": 2551, "end": 2724},
  {"id": "uhFob1qiNio", "title": "Trapse", "artist": "Trapse", "song": "Trapse", "genre": "JAZZ", "start": 2724, "end": 3200},
  {"id": "Onet82xMWdg", "title": "REID+WOLKEN — ᴅᴜɴᴇᴅɪɴ ᴊᴀᴢᴢ ʟᴏꜰᴛ: ɪɴᴅɪᴇ ᴠᴏɪᴄᴇꜱ ɪɪ", "artist": "REID+WOLKEN", "song": "REID+WOLKEN — ᴅᴜɴᴇᴅɪɴ ᴊᴀᴢᴢ ʟᴏꜰᴛ: ɪɴᴅɪᴇ ᴠᴏɪᴄᴇꜱ ɪɪ", "genre": "JAZZ", "start": 0, "end": 2207},
  {"id": "owx2gYYmElA", "title": "Sickboy", "artist": "Sickboy", "song": "Sickboy", "genre": "RAP", "start": 0, "end": 484},
  {"id": "owx2gYYmElA", "title": "Sickboy, Bubba44", "artist": "Sickboy, Bubba44", "song": "Sickboy, Bubba44", "genre": "RAP", "start": 484, "end": 790},
  {"id": "owx2gYYmElA", "title": "Sickboy, Bubba44, TeKahui - My Ride", "artist": "Sickboy, Bubba44, TeKahui", "song": "My Ride", "genre": "RAP", "start": 790, "end": 929},
  {"id": "owx2gYYmElA", "title": "Sickboy, KRIT", "artist": "Sickboy, KRIT", "song": "Sickboy, KRIT", "genre": "RAP", "start": 929, "end": 1276},
  {"id": "owx2gYYmElA", "title": "Sickboy, KRIT", "artist": "Sickboy, KRIT", "song": "Sickboy, KRIT", "genre": "RAP", "start": 1276, "end": 1487},
  {"id": "owx2gYYmElA", "title": "Sickboy, Krit, Alcatraz", "artist": "Sickboy, Krit, Alcatraz", "song": "Sickboy, Krit, Alcatraz", "genre": "RAP", "start": 1487, "end": 1716},
  {"id": "owx2gYYmElA", "title": "KRIT - M.I.K.", "artist": "KRIT", "song": "M.I.K.", "genre": "RAP", "start": 1716, "end": 1854},
  {"id": "owx2gYYmElA", "title": "KRIT Ft RYECHI - Homegrown", "artist": "KRIT Ft RYECHI", "song": "Homegrown", "genre": "RAP", "start": 1854, "end": 2013},
  {"id": "owx2gYYmElA", "title": "KRIT", "artist": "KRIT", "song": "KRIT", "genre": "RAP", "start": 2013, "end": 2150},
  {"id": "owx2gYYmElA", "title": "KRIT", "artist": "KRIT", "song": "KRIT", "genre": "RAP", "start": 2150, "end": 2251},
  {"id": "owx2gYYmElA", "title": "KICK IN THE DOOR (FREES)", "artist": "KICK IN THE DOOR (FREES)", "song": "KICK IN THE DOOR (FREES)", "genre": "RAP", "start": 2251, "end": 2490},
  {"id": "owx2gYYmElA", "title": "KRIT", "artist": "KRIT", "song": "KRIT", "genre": "RAP", "start": 2490, "end": 2704},
  {"id": "owx2gYYmElA", "title": "Sickboy, KRIT, Bubba44, S3FS", "artist": "Sickboy, KRIT, Bubba44, S3FS", "song": "Sickboy, KRIT, Bubba44, S3FS", "genre": "RAP", "start": 2704, "end": 2873},
  {"id": "owx2gYYmElA", "title": "Bubba44", "artist": "Bubba44", "song": "Bubba44", "genre": "RAP", "start": 2873, "end": 2970},
  {"id": "owx2gYYmElA", "title": "Bubba44, Sickboy", "artist": "Bubba44, Sickboy", "song": "Bubba44, Sickboy", "genre": "RAP", "start": 2970, "end": 3096},
  {"id": "owx2gYYmElA", "title": "Bubba44, Sickboy", "artist": "Bubba44, Sickboy", "song": "Bubba44, Sickboy", "genre": "RAP", "start": 3096, "end": 3258},
  {"id": "owx2gYYmElA", "title": "Bubba44", "artist": "Bubba44", "song": "Bubba44", "genre": "RAP", "start": 3258, "end": 3600},
  {"id": "owx2gYYmElA", "title": "Bubba44, Dita ur Friend", "artist": "Bubba44, Dita ur Friend", "song": "Bubba44, Dita ur Friend", "genre": "RAP", "start": 3600, "end": 3757},
  {"id": "owx2gYYmElA", "title": "Bubba44, Dita ur Friend", "artist": "Bubba44, Dita ur Friend", "song": "Bubba44, Dita ur Friend", "genre": "RAP", "start": 3757, "end": 3901},
  {"id": "owx2gYYmElA", "title": "Bubba44, Dita ur Friend", "artist": "Bubba44, Dita ur Friend", "song": "Bubba44, Dita ur Friend", "genre": "RAP", "start": 3901, "end": 3902},
  {"id": "YJhObEZSbdM", "title": "ALCATRAZ Live from Megazone", "artist": "ALCATRAZ Live from Megazone", "song": "ALCATRAZ Live from Megazone", "genre": "RAP", "start": 0, "end": 1072},
  {"id": "CLWMTujWHyc", "title": "TOUGH GUY - '28' live at The Crown, Dunedin", "artist": "TOUGH GUY", "song": "'28' live at The Crown, Dunedin", "genre": "RAP", "start": 0, "end": 273},
  {"id": "Q8BTkUb93uc", "title": "Memoirs", "artist": "MIC SURE", "song": "Memoirs", "genre": "RAP", "start": 0, "end": 117},
  {"id": "Q8BTkUb93uc", "title": "Cellar Door", "artist": "MIC SURE", "song": "Cellar Door", "genre": "RAP", "start": 117, "end": 168},
  {"id": "Q8BTkUb93uc", "title": "6 Pack", "artist": "MIC SURE", "song": "6 Pack", "genre": "RAP", "start": 168, "end": 328},
  {"id": "Q8BTkUb93uc", "title": "Big Ups", "artist": "MIC SURE", "song": "Big Ups", "genre": "RAP", "start": 328, "end": 412},
  {"id": "Q8BTkUb93uc", "title": "Watching Manu Fly", "artist": "MIC SURE", "song": "Watching Manu Fly", "genre": "RAP", "start": 412, "end": 600},
  {"id": "Q8BTkUb93uc", "title": "Part of me", "artist": "MIC SURE", "song": "Part of me", "genre": "RAP", "start": 600, "end": 738},
  {"id": "Q8BTkUb93uc", "title": "Accapella", "artist": "MIC SURE", "song": "Accapella", "genre": "RAP", "start": 738, "end": 786},
  {"id": "Q8BTkUb93uc", "title": "Why so Serious", "artist": "MIC SURE", "song": "Why so Serious", "genre": "RAP", "start": 786, "end": 980},
  {"id": "Q8BTkUb93uc", "title": "Celebrate", "artist": "MIC SURE", "song": "Celebrate", "genre": "RAP", "start": 980, "end": 1225},
  {"id": "AJ99tU3lqzQ", "title": "Party With A Nesian", "artist": "Party With A Nesian", "song": "Party With A Nesian", "genre": "RAP", "start": 0, "end": 226},
  {"id": "AJ99tU3lqzQ", "title": "Nesian like Me", "artist": "Nesian like Me", "song": "Nesian like Me", "genre": "RAP", "start": 226, "end": 476},
  {"id": "AJ99tU3lqzQ", "title": "Call U in the Morning (ft. Tyree)", "artist": "Call U in the Morning (ft. Tyree)", "song": "Call U in the Morning (ft. Tyree)", "genre": "RAP", "start": 476, "end": 684},
  {"id": "AJ99tU3lqzQ", "title": "Lovers & Friends", "artist": "Lovers & Friends", "song": "Lovers & Friends", "genre": "RAP", "start": 684, "end": 932},
  {"id": "oNo0vlT0UUQ", "title": "intro", "artist": "intro", "song": "intro", "genre": "RAP", "start": 0, "end": 96},
  {"id": "oNo0vlT0UUQ", "title": "to good freestyle.", "artist": "to good freestyle.", "song": "to good freestyle.", "genre": "RAP", "start": 96, "end": 286},
  {"id": "oNo0vlT0UUQ", "title": "Out on the hustle.", "artist": "Out on the hustle.", "song": "Out on the hustle.", "genre": "RAP", "start": 286, "end": 410},
  {"id": "oNo0vlT0UUQ", "title": "Chivalrys dead.", "artist": "Chivalrys dead.", "song": "Chivalrys dead.", "genre": "RAP", "start": 410, "end": 584},
  {"id": "oNo0vlT0UUQ", "title": "Shook ones freestyle.", "artist": "Shook ones freestyle.", "song": "Shook ones freestyle.", "genre": "RAP", "start": 584, "end": 787},
  {"id": "Np8OjWImk2E", "title": "Heavy Mentality", "artist": "Heavy Mentality", "song": "Heavy Mentality", "genre": "RAP", "start": 0, "end": 232},
  {"id": "Np8OjWImk2E", "title": "Scribe (Not many remix cypher)", "artist": "Scribe (Not many remix cypher)", "song": "Scribe (Not many remix cypher)", "genre": "RAP", "start": 232, "end": 455},
  {"id": "Np8OjWImk2E", "title": "Dopamine", "artist": "Dopamine", "song": "Dopamine", "genre": "RAP", "start": 455, "end": 687},
  {"id": "Np8OjWImk2E", "title": "DJ Premier (mashup Cypher)", "artist": "DJ Premier (mashup Cypher)", "song": "DJ Premier (mashup Cypher)", "genre": "RAP", "start": 687, "end": 958},
  {"id": "Np8OjWImk2E", "title": "Foul Swordplay", "artist": "Foul Swordplay", "song": "Foul Swordplay", "genre": "RAP", "start": 958, "end": 1163},
  {"id": "Np8OjWImk2E", "title": "Brainstorm", "artist": "Brainstorm", "song": "Brainstorm", "genre": "RAP", "start": 1163, "end": 1418},
  {"id": "gxxH73S1sac", "title": "Saturns Rings", "artist": "Saturns Rings", "song": "Saturns Rings", "genre": "RAP", "start": 0, "end": 148},
  {"id": "gxxH73S1sac", "title": "Blufyre", "artist": "Blufyre", "song": "Blufyre", "genre": "RAP", "start": 148, "end": 280},
  {"id": "gxxH73S1sac", "title": "Separate", "artist": "Separate", "song": "Separate", "genre": "RAP", "start": 280, "end": 405},
  {"id": "gxxH73S1sac", "title": "Flow is Physical", "artist": "Flow is Physical", "song": "Flow is Physical", "genre": "RAP", "start": 405, "end": 535},
  {"id": "gxxH73S1sac", "title": "Domination", "artist": "Domination", "song": "Domination", "genre": "RAP", "start": 535, "end": 674},
  {"id": "gxxH73S1sac", "title": "Ninja window", "artist": "Ninja window", "song": "Ninja window", "genre": "RAP", "start": 674, "end": 831},
  {"id": "gxxH73S1sac", "title": "Frontline", "artist": "Frontline", "song": "Frontline", "genre": "RAP", "start": 831, "end": 942},
  {"id": "gxxH73S1sac", "title": "Swords over war", "artist": "Swords over war", "song": "Swords over war", "genre": "RAP", "start": 942, "end": 1081},
  {"id": "gxxH73S1sac", "title": "Gholden Ghost", "artist": "Gholden Ghost", "song": "Gholden Ghost", "genre": "RAP", "start": 1081, "end": 1280},
  {"id": "7XTt8SivXyA", "title": "Benchmarks the Spot", "artist": "Benchmarks the Spot", "song": "Benchmarks the Spot", "genre": "RAP", "start": 11, "end": 272},
  {"id": "7XTt8SivXyA", "title": "Game Don't Wait", "artist": "Game Don't Wait", "song": "Game Don't Wait", "genre": "RAP", "start": 272, "end": 464},
  {"id": "7XTt8SivXyA", "title": "Real One", "artist": "Real One", "song": "Real One", "genre": "RAP", "start": 464, "end": 740},
  {"id": "7XTt8SivXyA", "title": "Highly Intoxicated", "artist": "Highly Intoxicated", "song": "Highly Intoxicated", "genre": "RAP", "start": 740, "end": 940},
  {"id": "7XTt8SivXyA", "title": "Last Decade", "artist": "Last Decade", "song": "Last Decade", "genre": "RAP", "start": 940, "end": 1159},
  {"id": "7XTt8SivXyA", "title": "'Who's who & what's what'", "artist": "'Who's who & what's what'", "song": "'Who's who & what's what'", "genre": "RAP", "start": 1159, "end": 1319},
  {"id": "7XTt8SivXyA", "title": "'What it's like'", "artist": "'What it's like'", "song": "'What it's like'", "genre": "RAP", "start": 1319, "end": 1562},
  {"id": "7XTt8SivXyA", "title": "'Do My Thang'", "artist": "'Do My Thang'", "song": "'Do My Thang'", "genre": "RAP", "start": 1562, "end": 1756},
  {"id": "7XTt8SivXyA", "title": "'Wave left to right'", "artist": "'Wave left to right'", "song": "'Wave left to right'", "genre": "RAP", "start": 1756, "end": 1982},
  {"id": "x4ihJ5iqSHY", "title": "Intro", "artist": "Intro", "song": "Intro", "genre": "RAP", "start": 0, "end": 20},
  {"id": "x4ihJ5iqSHY", "title": "TO PASTURES", "artist": "TO PASTURES", "song": "TO PASTURES", "genre": "RAP", "start": 20, "end": 204},
  {"id": "x4ihJ5iqSHY", "title": "GWOP", "artist": "GWOP", "song": "GWOP", "genre": "RAP", "start": 204, "end": 312},
  {"id": "x4ihJ5iqSHY", "title": "MULL IT UP", "artist": "MULL IT UP", "song": "MULL IT UP", "genre": "RAP", "start": 312, "end": 448},
  {"id": "x4ihJ5iqSHY", "title": "TERRESTRIAL", "artist": "TERRESTRIAL", "song": "TERRESTRIAL", "genre": "RAP", "start": 448, "end": 575},
  {"id": "x4ihJ5iqSHY", "title": "ALL OF THE MONEY PT.1", "artist": "ALL OF THE MONEY PT.1", "song": "ALL OF THE MONEY PT.1", "genre": "RAP", "start": 575, "end": 684},
  {"id": "x4ihJ5iqSHY", "title": "RESPITE", "artist": "RESPITE", "song": "RESPITE", "genre": "RAP", "start": 684, "end": 955},
  {"id": "x4ihJ5iqSHY", "title": "DIGGIN (GOLDMINES)", "artist": "DIGGIN (GOLDMINES)", "song": "DIGGIN (GOLDMINES)", "genre": "RAP", "start": 955, "end": 1143},
  {"id": "9PJUYLaJftE", "title": "Blue Collar Youngin'", "artist": "Blue Collar Youngin'", "song": "Blue Collar Youngin'", "genre": "RAP", "start": 0, "end": 107},
  {"id": "9PJUYLaJftE", "title": "Pass the Bill", "artist": "Pass the Bill", "song": "Pass the Bill", "genre": "RAP", "start": 107, "end": 280},
  {"id": "9PJUYLaJftE", "title": "M.i.k", "artist": "M.i.k", "song": "M.i.k", "genre": "RAP", "start": 280, "end": 417},
  {"id": "9PJUYLaJftE", "title": "Herbal Kiwiana", "artist": "Herbal Kiwiana", "song": "Herbal Kiwiana", "genre": "RAP", "start": 417, "end": 642},
  {"id": "9PJUYLaJftE", "title": "Weeds (ft. Bubba44, Sick Boy & Villain Flynn)", "artist": "Weeds (ft. Bubba44, Sick Boy & Villain Flynn)", "song": "Weeds (ft. Bubba44, Sick Boy & Villain Flynn)", "genre": "RAP", "start": 642, "end": 775},
  {"id": "9PJUYLaJftE", "title": "SouthSid3Sector", "artist": "SouthSid3Sector", "song": "SouthSid3Sector", "genre": "RAP", "start": 775, "end": 987},
  {"id": "9PJUYLaJftE", "title": "Intro / Kick in the door (freestyles)", "artist": "Intro / Kick in the door (freestyles)", "song": "Intro / Kick in the door (freestyles)", "genre": "RAP", "start": 987, "end": 1267},
  {"id": "OGuTg98uTjg", "title": "Windy city", "artist": "Windy city", "song": "Windy city", "genre": "RAP", "start": 0, "end": 194},
  {"id": "OGuTg98uTjg", "title": "Furious five", "artist": "Furious five", "song": "Furious five", "genre": "RAP", "start": 194, "end": 352},
  {"id": "OGuTg98uTjg", "title": "Money up", "artist": "Money up", "song": "Money up", "genre": "RAP", "start": 352, "end": 563},
  {"id": "OGuTg98uTjg", "title": "Life keeps moving", "artist": "Life keeps moving", "song": "Life keeps moving", "genre": "RAP", "start": 563, "end": 686},
  {"id": "OGuTg98uTjg", "title": "Rather be alone", "artist": "Rather be alone", "song": "Rather be alone", "genre": "RAP", "start": 686, "end": 856},
  {"id": "OGuTg98uTjg", "title": "Happy", "artist": "Happy", "song": "Happy", "genre": "RAP", "start": 856, "end": 1049},
  {"id": "OGuTg98uTjg", "title": "Positive and proud", "artist": "Positive and proud", "song": "Positive and proud", "genre": "RAP", "start": 1049, "end": 1217},
  {"id": "OGuTg98uTjg", "title": "Alright (Cover)", "artist": "Alright (Cover)", "song": "Alright (Cover)", "genre": "RAP", "start": 1217, "end": 1426},
  {"id": "d1XTFC4_x2U", "title": "H.A.A.R.P.", "artist": "H.A.A.R.P.", "song": "H.A.A.R.P.", "genre": "RAP", "start": 0, "end": 243},
  {"id": "d1XTFC4_x2U", "title": "Shining", "artist": "Shining", "song": "Shining", "genre": "RAP", "start": 243, "end": 448},
  {"id": "d1XTFC4_x2U", "title": "~Freestyle", "artist": "~Freestyle", "song": "~Freestyle", "genre": "RAP", "start": 448, "end": 543},
  {"id": "d1XTFC4_x2U", "title": "Wah Juan' Do", "artist": "Wah Juan' Do", "song": "Wah Juan' Do", "genre": "RAP", "start": 543, "end": 759},
  {"id": "d1XTFC4_x2U", "title": "Role Reversal", "artist": "Role Reversal", "song": "Role Reversal", "genre": "RAP", "start": 759, "end": 826},
  {"id": "d1XTFC4_x2U", "title": "Quantum Coin", "artist": "Quantum Coin", "song": "Quantum Coin", "genre": "RAP", "start": 826, "end": 943},
  {"id": "d1XTFC4_x2U", "title": "~Freestyle", "artist": "~Freestyle", "song": "~Freestyle", "genre": "RAP", "start": 943, "end": 1051},
  {"id": "d1XTFC4_x2U", "title": "?????? ????? (Unreleased)", "artist": "?????? ????? (Unreleased)", "song": "?????? ????? (Unreleased)", "genre": "RAP", "start": 1051, "end": 1197},
  {"id": "d1XTFC4_x2U", "title": "????????? (Unreleased)", "artist": "????????? (Unreleased)", "song": "????????? (Unreleased)", "genre": "RAP", "start": 1197, "end": 1370},
  {"id": "d1XTFC4_x2U", "title": "The Nucleus", "artist": "The Nucleus", "song": "The Nucleus", "genre": "RAP", "start": 1370, "end": 1530},
  {"id": "XqleQ6NP9oM", "title": "Soundscape (Karakia)", "artist": "Soundscape (Karakia)", "song": "Soundscape (Karakia)", "genre": "RAP", "start": 0, "end": 205},
  {"id": "XqleQ6NP9oM", "title": "Kai A Te Iro", "artist": "Kai A Te Iro", "song": "Kai A Te Iro", "genre": "RAP", "start": 205, "end": 434},
  {"id": "XqleQ6NP9oM", "title": "Whakakapia", "artist": "Whakakapia", "song": "Whakakapia", "genre": "RAP", "start": 434, "end": 663},
  {"id": "XqleQ6NP9oM", "title": "Hōhā Nei Au", "artist": "Hōhā Nei Au", "song": "Hōhā Nei Au", "genre": "RAP", "start": 663, "end": 906},
  {"id": "XqleQ6NP9oM", "title": "Huri Te Whenua", "artist": "Huri Te Whenua", "song": "Huri Te Whenua", "genre": "RAP", "start": 906, "end": 1046},
  {"id": "XqleQ6NP9oM", "title": "Rere", "artist": "Rere", "song": "Rere", "genre": "RAP", "start": 1046, "end": 1263},
  {"id": "XqleQ6NP9oM", "title": "Tāiro", "artist": "Tāiro", "song": "Tāiro", "genre": "RAP", "start": 1263, "end": 1699},
  {"id": "XqleQ6NP9oM", "title": "Oka", "artist": "Oka", "song": "Oka", "genre": "RAP", "start": 1699, "end": 1883},
  {"id": "XqleQ6NP9oM", "title": "Taipō", "artist": "Taipō", "song": "Taipō", "genre": "RAP", "start": 1883, "end": 2138},
  {"id": "XqleQ6NP9oM", "title": "Takataka", "artist": "Takataka", "song": "Takataka", "genre": "RAP", "start": 2138, "end": 2340},
  {"id": "XqleQ6NP9oM", "title": "Ai Ana Kai Horetātā", "artist": "Ai Ana Kai Horetātā", "song": "Ai Ana Kai Horetātā", "genre": "RAP", "start": 2340, "end": 2502},
  {"id": "XqleQ6NP9oM", "title": "Auraki Mai", "artist": "Auraki Mai", "song": "Auraki Mai", "genre": "RAP", "start": 2502, "end": 2736},
  {"id": "GoP7KiDgCkg", "title": "Dudstown Soundsystem — ŌHHH22", "artist": "Dudstown Soundsystem", "song": "Dudstown Soundsystem — ŌHHH22", "genre": "RAP", "start": 0, "end": 1970},
  {"id": "4SbVszlEw3Y", "title": "King Homeboy — ŌHHH22", "artist": "King Homeboy", "song": "King Homeboy — ŌHHH22", "genre": "RAP", "start": 0, "end": 1772},
  {"id": "wIlck2PsFVM", "title": "Local Elementz & Roarz — ŌHHH22", "artist": "Local Elementz & Roarz", "song": "Local Elementz & Roarz — ŌHHH22", "genre": "RAP", "start": 0, "end": 1969},
  {"id": "xX6NIpgr8WA", "title": "Thanks — ŌHHH22", "artist": "Thanks", "song": "Thanks — ŌHHH22", "genre": "RAP", "start": 0, "end": 990},
  {"id": "Q4ggmJTPSsI", "title": "TO PASTURES", "artist": "TO PASTURES", "song": "TO PASTURES", "genre": "RAP", "start": 0, "end": 185},
  {"id": "Q4ggmJTPSsI", "title": "DEAR CHCH", "artist": "DEAR CHCH", "song": "DEAR CHCH", "genre": "RAP", "start": 185, "end": 354},
  {"id": "Q4ggmJTPSsI", "title": "GWOP", "artist": "GWOP", "song": "GWOP", "genre": "RAP", "start": 354, "end": 510},
  {"id": "Q4ggmJTPSsI", "title": "ALL OF THE MONEY PT.1", "artist": "ALL OF THE MONEY PT.1", "song": "ALL OF THE MONEY PT.1", "genre": "RAP", "start": 510, "end": 631},
  {"id": "Q4ggmJTPSsI", "title": "TERRESTRIAL", "artist": "TERRESTRIAL", "song": "TERRESTRIAL", "genre": "RAP", "start": 631, "end": 996},
  {"id": "Q4ggmJTPSsI", "title": "DIGGIN (GOLDMINES)", "artist": "DIGGIN (GOLDMINES)", "song": "DIGGIN (GOLDMINES)", "genre": "RAP", "start": 996, "end": 1194},
  {"id": "j0xmcfdur6s", "title": "PHX & Foul Play Syndicate — ŌHHH22", "artist": "PHX & Foul Play Syndicate", "song": "PHX & Foul Play Syndicate — ŌHHH22", "genre": "RAP", "start": 0, "end": 1670},
  {"id": "6bk7ezTvfNs", "title": "ALXG — ŌHHH22", "artist": "ALXG", "song": "ALXG — ŌHHH22", "genre": "RAP", "start": 0, "end": 943},
  {"id": "Q_LUqcNwt1E", "title": "Optimist Mind — ŌHHH22", "artist": "Optimist Mind", "song": "Optimist Mind — ŌHHH22", "genre": "RAP", "start": 0, "end": 1456},
  {"id": "t3S_1owNgg0", "title": "Tali Joy — ŌHHH22", "artist": "Tali Joy", "song": "Tali Joy — ŌHHH22", "genre": "RAP", "start": 0, "end": 1333},
  {"id": "nmoTBVEOmPQ", "title": "Christian Tucker — ŌHHH22", "artist": "Christian Tucker", "song": "Christian Tucker — ŌHHH22", "genre": "RAP", "start": 0, "end": 942},
  {"id": "-ZsnEJllT5Y", "title": "Rye Chi (ft. Ridge Jaggers) — To Pastures (Music for People)", "artist": "Rye Chi (ft. Ridge Jaggers)", "song": "Rye Chi (ft. Ridge Jaggers) — To Pastures (Music for People)", "genre": "RAP", "start": 0, "end": 173},
  {"id": "fooylLMs62w", "title": "THIS TIME", "artist": "THIS TIME", "song": "THIS TIME", "genre": "RNB", "start": 0, "end": 167},
  {"id": "fooylLMs62w", "title": "FTF", "artist": "FTF", "song": "FTF", "genre": "RNB", "start": 167, "end": 335},
  {"id": "fooylLMs62w", "title": "MIDNIGHT LADY ft.VAYNE", "artist": "MIDNIGHT LADY ft.VAYNE", "song": "MIDNIGHT LADY ft.VAYNE", "genre": "RNB", "start": 335, "end": 542},
  {"id": "fooylLMs62w", "title": "DELEGATION", "artist": "DELEGATION", "song": "DELEGATION", "genre": "RNB", "start": 542, "end": 736},
  {"id": "fooylLMs62w", "title": "WYW", "artist": "WYW", "song": "WYW", "genre": "RNB", "start": 736, "end": 888},
  {"id": "fooylLMs62w", "title": "GIRLS LIKE ME ft.VAYNE", "artist": "GIRLS LIKE ME ft.VAYNE", "song": "GIRLS LIKE ME ft.VAYNE", "genre": "RNB", "start": 888, "end": 1050},
  {"id": "fooylLMs62w", "title": "PARTYNEXTDOOR", "artist": "PARTYNEXTDOOR", "song": "PARTYNEXTDOOR", "genre": "RNB", "start": 1050, "end": 1285},
  {"id": "fooylLMs62w", "title": "BEFORE I LEAVE", "artist": "BEFORE I LEAVE", "song": "BEFORE I LEAVE", "genre": "RNB", "start": 1285, "end": 1465},
  {"id": "PlNc_NrxXS0", "title": "Cocoon", "artist": "Cocoon", "song": "Cocoon", "genre": "RNB", "start": 0, "end": 229},
  {"id": "PlNc_NrxXS0", "title": "Coulda Shoulda Woulda", "artist": "Coulda Shoulda Woulda", "song": "Coulda Shoulda Woulda", "genre": "RNB", "start": 229, "end": 397},
  {"id": "PlNc_NrxXS0", "title": "Haunting Me", "artist": "Haunting Me", "song": "Haunting Me", "genre": "RNB", "start": 397, "end": 687},
  {"id": "PlNc_NrxXS0", "title": "Real-life Fantasy", "artist": "Real-life Fantasy", "song": "Real-life Fantasy", "genre": "RNB", "start": 687, "end": 898},
  {"id": "PlNc_NrxXS0", "title": "Times Been Hard", "artist": "Times Been Hard", "song": "Times Been Hard", "genre": "RNB", "start": 898, "end": 1053},
  {"id": "PlNc_NrxXS0", "title": "Time", "artist": "Time", "song": "Time", "genre": "RNB", "start": 1053, "end": 1328},
  {"id": "PlNc_NrxXS0", "title": "Start Over", "artist": "Start Over", "song": "Start Over", "genre": "RNB", "start": 1328, "end": 1552},
  {"id": "6TmjOxhDWps", "title": "ZExII — ŌHHH22", "artist": "ZExII", "song": "ZExII — ŌHHH22", "genre": "RNB", "start": 0, "end": 1101},
  {"id": "aa9fgOvASJA", "title": "Dubious Groove - Lobofest '21", "artist": "Dubious Groove", "song": "Lobofest '21", "genre": "RNB", "start": 0, "end": 1345},
  {"id": "O6e3xm1P3gc", "title": "Hocus Pocus", "artist": "Hocus Pocus", "song": "Hocus Pocus", "genre": "ROCK", "start": 0, "end": 394},
  {"id": "O6e3xm1P3gc", "title": "Christmas Time", "artist": "Christmas Time", "song": "Christmas Time", "genre": "ROCK", "start": 394, "end": 700},
  {"id": "O6e3xm1P3gc", "title": "Let me sleep", "artist": "Let me sleep", "song": "Let me sleep", "genre": "ROCK", "start": 700, "end": 983},
  {"id": "O6e3xm1P3gc", "title": "The Fairies Outnumber The Trolls", "artist": "The Fairies Outnumber The Trolls", "song": "The Fairies Outnumber The Trolls", "genre": "ROCK", "start": 983, "end": 1778},
  {"id": "wjsr8ZmaRVA", "title": "Chimney Ethics", "artist": "Chimney Ethics", "song": "Chimney Ethics", "genre": "ROCK", "start": 0, "end": 359},
  {"id": "wjsr8ZmaRVA", "title": "Pliers", "artist": "Pliers", "song": "Pliers", "genre": "ROCK", "start": 359, "end": 791},
  {"id": "wjsr8ZmaRVA", "title": "Phillips Head", "artist": "Phillips Head", "song": "Phillips Head", "genre": "ROCK", "start": 791, "end": 1128},
  {"id": "wjsr8ZmaRVA", "title": "Tuskrider", "artist": "Tuskrider", "song": "Tuskrider", "genre": "ROCK", "start": 1128, "end": 1520},
  {"id": "wjsr8ZmaRVA", "title": "Teeth", "artist": "Teeth", "song": "Teeth", "genre": "ROCK", "start": 1520, "end": 1943},
  {"id": "wjsr8ZmaRVA", "title": "Captain Aᵇ", "artist": "Captain Aᵇ", "song": "Captain Aᵇ", "genre": "ROCK", "start": 1943, "end": 2358},
  {"id": "wjsr8ZmaRVA", "title": "Red Eve", "artist": "Red Eve", "song": "Red Eve", "genre": "ROCK", "start": 2358, "end": 2680},
  {"id": "XNdZ249SJlU", "title": "White lies", "artist": "White lies", "song": "White lies", "genre": "ROCK", "start": 0, "end": 254},
  {"id": "XNdZ249SJlU", "title": "Ashton", "artist": "Ashton", "song": "Ashton", "genre": "ROCK", "start": 254, "end": 645},
  {"id": "XNdZ249SJlU", "title": "4 walls", "artist": "4 walls", "song": "4 walls", "genre": "ROCK", "start": 645, "end": 1094},
  {"id": "XNdZ249SJlU", "title": "Phase", "artist": "Phase", "song": "Phase", "genre": "ROCK", "start": 1094, "end": 1369},
  {"id": "XNdZ249SJlU", "title": "Bed", "artist": "Bed", "song": "Bed", "genre": "ROCK", "start": 1369, "end": 1560},
  {"id": "XNdZ249SJlU", "title": "Wake up", "artist": "Wake up", "song": "Wake up", "genre": "ROCK", "start": 1560, "end": 1877},
  {"id": "XNdZ249SJlU", "title": "She got it", "artist": "She got it", "song": "She got it", "genre": "ROCK", "start": 1877, "end": 2288},
  {"id": "XNdZ249SJlU", "title": "Sunny afternoon", "artist": "Sunny afternoon", "song": "Sunny afternoon", "genre": "ROCK", "start": 2288, "end": 2578},
  {"id": "XNdZ249SJlU", "title": "Little green friend", "artist": "Little green friend", "song": "Little green friend", "genre": "ROCK", "start": 2578, "end": 3092},
  {"id": "XNdZ249SJlU", "title": "Believe", "artist": "Believe", "song": "Believe", "genre": "ROCK", "start": 3092, "end": 3450},
  {"id": "TXrevEe3yAA", "title": "Cuck (Live From The Crown)", "artist": "Cuck (Live From The Crown)", "song": "Cuck (Live From The Crown)", "genre": "ROCK", "start": 0, "end": 801},
  {"id": "YqwxL_QmpyA", "title": "Glad Rabbit - Lobofest '21", "artist": "Glad Rabbit", "song": "Lobofest '21", "genre": "ROCK", "start": 0, "end": 1368},
  {"id": "cKEdGuT74N4", "title": "The Big Lawn - Lobofest '21", "artist": "The Big Lawn", "song": "Lobofest '21", "genre": "ROCK", "start": 0, "end": 1116},
  {"id": "lCVuGcLU-fo", "title": "Les Marionettes (The Lucky Ones) - Lobofest '21", "artist": "Les Marionettes (The Lucky Ones)", "song": "Lobofest '21", "genre": "ROCK", "start": 0, "end": 1372},
  {"id": "X1-uLV4BgHU", "title": "Bulletproof Convertible - Lobofest '21", "artist": "Bulletproof Convertible", "song": "Lobofest '21", "genre": "ROCK", "start": 0, "end": 1516},
  {"id": "QyXhMzLURKk", "title": "Fre3dom - Lobofest '21", "artist": "Fre3dom", "song": "Lobofest '21", "genre": "ROCK", "start": 0, "end": 1267},
  {"id": "6sB8vvA_6rQ", "title": "Bo and The Constrictors - Lobofest '21", "artist": "Bo and The Constrictors", "song": "Lobofest '21", "genre": "ROCK", "start": 0, "end": 1593},
  {"id": "wVFA4gm0K8Q", "title": "Ollie & The Crooks - Lobofest '21", "artist": "Ollie & The Crooks", "song": "Lobofest '21", "genre": "ROCK", "start": 0, "end": 1536},
  {"id": "edl2kqLY5jQ", "title": "Dylbag - Lobofest '21", "artist": "Dylbag", "song": "Lobofest '21", "genre": "ROCK", "start": 0, "end": 1320},
  {"id": "Yc2LRN-s8Kg", "title": "One Day Sane - Lobofest '21", "artist": "One Day Sane", "song": "Lobofest '21", "genre": "ROCK", "start": 0, "end": 1050},
  {"id": "HRD7URbSoRc", "title": "Mads Harrop - Lobofest '21", "artist": "Mads Harrop", "song": "Lobofest '21", "genre": "ROCK", "start": 0, "end": 1298},
  {"id": "y4jkCeM_hDo", "title": "Rezzy Crooks — Swimming Pools (Cover) (Music for People)", "artist": "Rezzy Crooks", "song": "Rezzy Crooks — Swimming Pools (Cover) (Music for People)", "genre": "ROCK", "start": 0, "end": 287},
  {"id": "t3BjeWZtcdg", "title": "The Rhododendrons — The Apple (𝘧𝘳𝘰𝘮 𝘵𝘩𝘦 𝘱𝘭𝘢𝘤𝘦)", "artist": "The Rhododendrons", "song": "The Rhododendrons — The Apple (𝘧𝘳𝘰𝘮 𝘵𝘩𝘦 𝘱𝘭𝘢𝘤𝘦)", "genre": "ROCK", "start": 0, "end": 247},
];